### ISSUE TITLE
Server Error in Kudu after typing hookurl

### ISSUE THREAD

**Issue by natanielcz** [WCOMAB/KuduPostDeploymentSlackHook#1]
After deploying to azure I get Server Error in Kudu. Have you any idea what can cause this error?

Kudu settings for website which for which I want to enable notifications
![image](https://cloud.githubusercontent.com/assets/1231703/10044082/3347b78c-61f8-11e5-9b9f-5b7cb29cfc73.png)

App from your project has following App settings
![image](https://cloud.githubusercontent.com/assets/1231703/10044105/65940952-61f8-11e5-9d05-8f0171cb2952.png)

Is there anything else what I should do to ake it working?

**Comment by devlead** [comment]
@natanielcz is it an obfuscated url above?

The in your other web sites you go in to each and enter the url of the new `KuduPostDeploymentSlackHook` web you have setup i.e. `https://kudupostdeploymentslackhook.azurewebsites.net/`

If you surf into your `https://kudupostdeploymentslackhook.azurewebsites.net/` you should see:
`WCOM AB - Kudu Post Deployment Slack Hook`

Then web hook on each web (can't be the same as to try to deploy too) i.e.
https://[yoursite.scm].azurewebsites.net/WebHooks it should look something like this:
![image](https://cloud.githubusercontent.com/assets/1647294/10047489/bb36026e-620e-11e5-942e-e906fdb378b0.png)

You could try to upgrade Node version, you do that by changing the above `WEBSITE_NODE_DEFAULT_VERSION` to i.e.`0.12.6` the default `0.10.32` is quiet old now.

**Comment by natanielcz** [comment]
@devlead : now i see the problem. I put here url to hooks.slack.com/*** instead of url of your project. Now it works great. 

Could You please tell me that is there a possibility to notify also when deployment starts?

**Comment by devlead** [comment]
@natanielcz superb that it got sorted.

If you do deployment via source control Bitbucket, Github, VSO, etc. offers web hooks for web code is pushed and connectors for Slack already exist there.

Kudu doesn't expose a pre-deployment hook yet, what you can do if you want deployment to start with a notification to Slack is to do your own custom deployment script, where you either user Node or PowerShell's Invoke-RestMethod.

I've been working on a more advanced deployment script scenarios where I utilize the powers of Roslyn & C# via a tool called [Cake](https://github.com/cake-build/cake), which has add-ins for Slack which makes it quite easy to communicate with Slack.
More info Cake.Kudu add-in here:
https://github.com/WCOMAB/Cake.Kudu

**Comment by natanielcz** [comment]
@devlead : I'm doing deployments via Bitbucket but I was wondering to put only simple information: "Deployment has been started" for testers instead of full commit information.

I also use custom deployment script and I think that maybe I'll edit it to collaborate with Slack as You mentioned. 

Cake.Kudu looks nice. I think that when I'll find some spare time I'll check it out on seperate branch ;) Keep working on that ;)

**Comment by devlead** [comment]
@natanielcz as node is installed on Kudu you could probably use the [slack.js](https://github.com/WCOMAB/KuduPostDeploymentSlackHook/blob/master/slack.js) module I've written for the web hook.

Or if you just want something quick n dirty you could use the [test.js](https://github.com/WCOMAB/KuduPostDeploymentSlackHook/blob/master/test.js), customize the JSON payload and post to your KuduPostDeploymentSlackHook

**Comment by natanielcz** [comment]
If I now how to Post data to Slack I think that I'll make any cmd file which will do that and which will send POST messages on few deployment stages. 

Thanks for Your engagement and support ;)
