### ISSUE TITLE
A task was cancelled

### ISSUE THREAD

**Issue by GerjanOnline** [WCOMAB/KuduPostDeploymentSlackHook#2]
I'm getting the following error:

![image](https://cloud.githubusercontent.com/assets/1153419/13458395/56392764-e06d-11e5-8552-85548907db45.png)

What I did:
1. Created an incoming webhook in Slack
2. On `https://manage.windowsazure.com` I put this webhook url in `app settings` => `slackhookuri` : `https://hooks.slack.com/services/[key]`
3. Added `https://kudupostdeploymentslackhook.azurewebsites.net/` to `https://[mysite].scm.azurewebsites.net/WebHooks`

What am I doing wrong? Should i use  `https://kudupostdeploymentslackhook.azurewebsites.net/` ? How can I debug the error?

**Comment by devlead** [comment]
@GerjanOnline You should use the url of the site you have deployed the KuduPostDeploymentSlackHook web too, which should be the web you have configured the environment variable on.

You can try surfing to the configured slack hook uri, you should receive `No payload received` if the incoming web hook is active at Slack.

If you just surf to your "KuduPostDeploymentSlackHook" you should see the text `WCOM AB - Kudu Post Deployment Slack Hook`

You can also try to call the web "KuduPostDeploymentSlackHook" with kudu payload with i.e. the PowerShell below
```powershell
$json = '{
   "id": "2bdc42572263361fef1a3334c562be57dfb06c27",
   "status": "success",
   "statusText": "",
   "authorEmail": "test@test.com",
   "author": "John Doe",
   "message": "Epic new feature!",
   "progress": "",
   "deployer": "",
   "receivedTime": "2015-06-11T09:58:46.9983824Z",
   "startTime": "2015-06-11T10:39:02.1322211Z",
   "endTime": "2015-06-11T10:39:07.555094Z",
   "lastSuccessEndTime": "2015-06-11T10:39:07.555094Z",
   "complete": true,
   "siteName": "azure-dummy-site"
}'

Invoke-RestMethod -Method Post -Body $json -ContentType 'application/json' -Uri 'https://{your azure web post deployment app}.azurewebsites.net' -TimeoutSec 50
```
(there's also a node test file [here](https://github.com/WCOMAB/KuduPostDeploymentSlackHook/blob/master/test.js) if you prefer that, just change port and host then `node test.js`)

**Comment by GerjanOnline** [comment]
Works! Thank you!

**Comment by devlead** [comment]
@GerjanOnline superb :+1:
