### ISSUE TITLE
Deployed web app just throws 500 Internal Error

### ISSUE THREAD

**Issue by MarkBird** [WCOMAB/KuduPostDeploymentSlackHook#7]
Clicked button Deploy To Azure, which successfully created a Web App at https://kudupostdeploymentslackhookbf28.azurewebsites.net/

It just throws an internal error if you navigate to it, and the same when the post deployment web hook tries to post to it:

https://kudupostdeploymentslackhookbf28.azurewebsites.net/ | PostDeployment | 2018-05-03T13:56:20.7848572Z | InternalServerError | Internal Server Error
-- | -- | -- | -- | --

Is this no longer compatible with Azure?

**Comment by devlead** [comment]
Have you done the configuration as per stated here?
https://github.com/WCOMAB/KuduPostDeploymentSlackHook#configuration

**Comment by MarkBird** [comment]
Just had another go at this and it worked fine this time, so I obviously got the configuration wrong last time - sorry!

**Comment by devlead** [comment]
Great that you got it working 👍
